# Dependabot configuration for GitHub profile updates
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Mexico_City'
    open-pull-requests-limit: 10
    reviewers:
      - 'IsmaellHV'
    assignees:
      - 'IsmaellHV'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Mexico_City'
    open-pull-requests-limit: 10
    reviewers:
      - 'IsmaellHV'
    assignees:
      - 'IsmaellHV'
    commit-message:
      prefix: 'ci'
      include: 'scope'
